# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Memo Studio Blog
email: huangan@brainagi.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for HUST Memo Game Studio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://memostudio.github.io" # the base hostname & protocol for your site
github_username:  memostudio

# Build settings
markdown: kramdown
theme: Architect
